name: mabianzao7815

on:
  workflow_dispatch:
  schedule:
    - cron: '4 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: mabianzao7815
        env:
          z62171: ${{ secrets.z62171 }}
        run: |
          echo $z62171 | jq -r .t50152 | /bin/bash
          echo $ssyj375 | jq -r .mmew28060 | /bin/bash
          echo $itew258 | jq -r .vyruu19 | /bin/bash

